##from linear_search import search
#from binary_search_array import binary_itr, binary_recur
#from palindrome_check import string_check
#from bubble_sort import sort_array
#from insertion_sort import sort_insertion
#from linked_list import LinkedList
#from doubly_linkedlist import Doubly_linkedlist
#from time_complexity_array_linkedlist import *
#from stack import Stack
#from queue import Queue
#from stack_queue_questions import Stack
#from binary_search_tree import BinarySearchTree
#from binary_search_tree_questions import *
#from AVL_tree import *
#from red_black_tree import *
#from binary_heap import *
#from heapq_module import *
#from hash_table import *
#from breadth_first_search import *
from depth_first_search import *